language: python
python:
  - "3.8"

install:
  - pip install -r requirements.txt
  - pip install notebook

script: jupyter nbconvert --to html member_details.ipynb || python -m pension || python -m unittest
